# Generated by Django 5.2 on 2025-05-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0002_rename_context_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='context',
            field=models.TextField(blank=True, null=True),
        ),
    ]
