# Generated by Django 5.1.2 on 2025-05-14 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_receiver_share_recipient'),
        ('inbox', '0003_message_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.userposts'),
        ),
    ]
