version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: connectify-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: connectify
      MYSQL_USER: rashik
      MYSQL_PASSWORD: rashik123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    container_name: connectify-web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1

volumes:
  mysql_data:
