# Generated by Django 5.2 on 2025-05-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_userprofile_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='college_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
