# Generated by Django 5.2 on 2025-05-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_userprofile_bio_userprofile_college_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='college_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
