# Generated by Django 5.2 on 2025-04-24 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userposts',
            old_name='users',
            new_name='user',
        ),
    ]
