# Generated by Django 5.1.2 on 2025-05-11 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_comment_like'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_at', models.DateTimeField(auto_now_add=True)),
                ('orginal_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_by', to='home.userposts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
