# Generated by Django 5.1.2 on 2025-05-12 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_share'),
    ]

    operations = [
        migrations.RenameField(
            model_name='share',
            old_name='orginal_post',
            new_name='original_post',
        ),
    ]
