# Generated by Django 5.1.2 on 2025-05-14 12:54

from django.db import migrations,models


def set_default_sender(apps, schema_editor):
    Share = apps.get_model('home', 'Share')
    User = apps.get_model('auth', 'User')
    default_user = User.objects.first()  # Or use a specific user ID like `User.objects.get(id=1)`
    
    # Update any Share records where sender_id is null
    Share.objects.filter(sender_id__isnull=True).update(sender_id=default_user)

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_share_user_share_message_share_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='sender',
            field=models.ForeignKey(
                on_delete=models.CASCADE,
                to='auth.User',
                related_name='sent_shares',
                default=1  # Optional: You can set a default here too, if needed
            ),
        ),
        migrations.RunPython(set_default_sender),
    ]
