# Generated by Django 5.1.2 on 2025-05-14 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20250514_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='share',
            old_name='receiver',
            new_name='recipient',
        ),
    ]
